USE HOSPITAL;
SELECT CON.ID_CONSULTA, CON.DATA_CONS DATA, CON.HORA_CONS HORA, MED.NOME MEDICO, PAC.NOME PACIENTE
FROM CONSULTAS CON
INNER JOIN MEDICOS MED 
ON MED.CRM = CON.CRM AND MED.UF = CON.UF
INNER JOIN PACIENTES PAC 
ON PAC.CPF_PACIENTE = CON.CPF_PACIENTE;

SELECT PAC.NOME PACIENTE, COUNT(*) AS CONSULTAS
FROM CONSULTAS CON RIGHT JOIN PACIENTES PAC 
ON PAC.CPF_PACIENTE = CON.CPF_PACIENTE
GROUP BY PACIENTE;

SELECT DISTINCT DEPTO.NOME_ESPECIALIDADE
FROM DEPARTAMENTOS DEPTO
INNER JOIN MEDICOS MED 
ON MED.DEPTO_COD_ESPEC = DEPTO.COD_ESPECIALIDADE
INNER JOIN CONSULTAS CON 
ON MED.CRM = CON.CRM AND MED.UF = CON.UF
WHERE YEAR(CON.DATA_CONS) = 2024;

SELECT NOME, EMAIL
FROM MEDICOS
WHERE TELEFONE IS NULL OR TELEFONE = '';

SELECT DISTINCT PAC.NOME
FROM PACIENTES PAC
INNER JOIN CONSULTAS CON
ON PAC.CPF_PACIENTE = CON.CPF_PACIENTE
INNER JOIN MEDICOS MED
ON CON.CRM = MED.CRM AND CON.UF = MED.UF
INNER JOIN DEPARTAMENTOS DEPTO
ON DEPTO.COD_ESPECIALIDADE = MED.DEPTO_COD_ESPEC
WHERE DEPTO.NOME_ESPECIALIDADE = 'CARDIOLOGIA';

SELECT ESPEC AS ESPECIALIDADE, ROUND(AVG(QUANT),2) AS MEDIA
FROM (
		SELECT DEPTO.NOME_ESPECIALIDADE AS ESPEC,
		COUNT(ID_CONSULTA) AS QUANT FROM CONSULTAS CON
		INNER JOIN MEDICOS MED
		ON CON.CRM = MED.CRM AND CON.UF = MED.UF
		INNER JOIN DEPARTAMENTOS DEPTO
		ON DEPTO.COD_ESPECIALIDADE = MED.DEPTO_COD_ESPEC
		GROUP BY DEPTO.NOME_ESPECIALIDADE) AS BASE
GROUP BY ESPEC;

SELECT PACIENTE,CPF, CONCAT(ROUND((QTDE_PAC/QTDE_GERAL)*100,1),'%') AS PORCENTAGEM
FROM (
      SELECT PAC.NOME AS PACIENTE, 
	    PAC.CPF_PACIENTE AS CPF, 
	    COUNT(CONS.ID_CONSULTA) AS QTDE_PAC
	    FROM PACIENTES PAC
	    LEFT JOIN CONSULTAS CONS
	    ON PAC.CPF_PACIENTE = CONS.CPF_PACIENTE
	    GROUP BY PACIENTE
                        ) AS QUANTIDADE_POR_PACIENTE,
	  (	
      SELECT COUNT(*) AS QTDE_GERAL
      FROM CONSULTAS
                        ) AS QUANTIDADE_TOTAL
GROUP BY PACIENTE;